/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static clases.ConexionBD.conectarBD;
import static clases.ConexionBD.desconectarBD;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Luis
 */
public class Clientes extends javax.swing.JFrame {
    
    private String accion ="";
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        
        Image icon = new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage();
        setIconImage(icon);
        
        cargarTabla("");
    }
     /*--------------------------------------------------------------------------------------------------
        MIS METODOS
        */
    
     public void cargarTabla(String condicion)
        {
            Connection con = conectarBD();
            ResultSet   rs = null;
            String[]   titulos = {"Ibs","apellidos","Nombres","Municipio","Direccion","Telefono","Celular"};
            Object[]  fila = new Object[7]; 
            DefaultTableModel modelo = new DefaultTableModel(null,titulos);
            
            String sSQL  = "SELECT * FROM clientes"+condicion;
            
            try {
                
                PreparedStatement pst = con.prepareStatement(sSQL);
                rs=pst.executeQuery();
                
                while(rs.next ())
                {
                    fila[0] = rs.getString("ibs");
                    fila[1] = rs.getString("apellidos");
                    fila[2] = rs.getString("nombres");
                    fila[3] = rs.getString("municipio");
                    fila[4] = rs.getString("direccion");
                    fila[5] = rs.getString("telefono");
                    fila[6] = rs.getString("celular");
                    modelo.addRow(fila);
                }  
                
                jtb_Clientes.setModel(modelo);
            } 
            catch (Exception e) 
            {
            }
            desconectarBD();
        }
        
        public void mostrarDialogo()
        {
           Image icon = new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage();
           jdi_Clientes.setIconImage(icon);
           jdi_Clientes.setLocationRelativeTo(this);
           jdi_Clientes.setSize(550,350);
           jdi_Clientes.setVisible(true);
        }
        
        public void setControles(boolean activo)
        {
           txt_Ibs.setEditable(activo);
           txt_Nombres.setEditable(activo);
           txt_Direccion.setEditable(activo);
           txt_Telefono.setEditable(activo);
           txt_Municipio.setEditable(activo);
           txt_Celular.setEditable(activo);
           txt_Apellido.setEditable(activo);
        }
        
        public void limpiarControles()
         
        {
            txt_Ibs.setText("");
            txt_Nombres.setText("");
            txt_Direccion.setText("");
            txt_Telefono.setText("");
            txt_Municipio.setText("");
            txt_Celular.setText("");
            txt_Apellido.setText("");
        }
        
        public boolean cargarDialogo()
        {
         int fila = jtb_Clientes.getSelectedRow();  
        
        if( fila == -1 ) 
        {
            JOptionPane.showMessageDialog(null,"Debe seleccionar el Cliente","Atencion",JOptionPane.WARNING_MESSAGE ); 
            return false;
        }
        else
        {
            DefaultTableModel modelo = new DefaultTableModel();
            
            modelo = (DefaultTableModel) jtb_Clientes.getModel();
            
            txt_Ibs.setText( modelo.getValueAt(fila,0).toString());
            txt_Nombres.setText( modelo.getValueAt(fila,1).toString());
            txt_Direccion.setText( modelo.getValueAt(fila,2).toString() );
            txt_Telefono.setText( modelo.getValueAt(fila,3).toString());
            txt_Municipio.setText( modelo.getValueAt(fila,4).toString());
            txt_Celular.setText( modelo.getValueAt(fila,5).toString());
            txt_Apellido.setText( modelo.getValueAt(fila,6).toString());
            
            
            
            return true;
         }  
    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdi_Clientes = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txt_Ibs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Municipio = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Celular = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        cmb_Buscar = new javax.swing.JComboBox();
        btn_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Clientes = new javax.swing.JTable();
        btn_Adicionar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_CerrarClientes = new javax.swing.JButton();

        jLabel3.setText("IBS:");

        txt_Ibs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IbsKeyTyped(evt);
            }
        });

        jLabel4.setText("Apellidos:");

        txt_Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombres");

        txt_Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombresKeyTyped(evt);
            }
        });

        jLabel6.setText("Municipio:");

        jLabel7.setText("Direccion:");

        jLabel8.setText("Telefono:");

        txt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoKeyTyped(evt);
            }
        });

        jLabel9.setText("Celular:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");

        btn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Cliente");

        javax.swing.GroupLayout jdi_ClientesLayout = new javax.swing.GroupLayout(jdi_Clientes.getContentPane());
        jdi_Clientes.getContentPane().setLayout(jdi_ClientesLayout);
        jdi_ClientesLayout.setHorizontalGroup(
            jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdi_ClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(55, 55, 55)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jdi_ClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdi_ClientesLayout.createSequentialGroup()
                        .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jdi_ClientesLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_ClientesLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_ClientesLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(5, 5, 5)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_ClientesLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(9, 9, 9)))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Ibs, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Apellido)
                            .addComponent(txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdi_ClientesLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Direccion)
                                    .addComponent(txt_Municipio, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_Celular, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jdi_ClientesLayout.createSequentialGroup()
                        .addComponent(btn_Aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btn_Cerrar)
                        .addGap(19, 19, 19))))
        );
        jdi_ClientesLayout.setVerticalGroup(
            jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_ClientesLayout.createSequentialGroup()
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdi_ClientesLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel10))
                    .addGroup(jdi_ClientesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)))
                .addGap(30, 30, 30)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Ibs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Nombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Municipio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Celular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jdi_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Cerrar))
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Clientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar:");

        cmb_Buscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "ibs", "Apellidos", "Nombres", "Municipio", "Direccion", "Telefono", "Celular" }));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        jtb_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtb_Clientes);

        btn_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adicionar.png"))); // NOI18N
        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_CerrarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_CerrarClientes.setText("Cerrar");
        btn_CerrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(btn_CerrarClientes))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_Buscar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Buscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Adicionar)
                    .addComponent(btn_Editar)
                    .addComponent(btn_Eliminar)
                    .addComponent(btn_CerrarClientes))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        
        if( cargarDialogo())
          {
             accion = "MODIFICAR";
             setControles(true);
             txt_Ibs.setEditable(false);
             mostrarDialogo();
          }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        
        accion ="ADICIONAR";
        mostrarDialogo();
        setControles(true);
        limpiarControles();
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        jdi_Clientes.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        
        if( cargarDialogo())
          {
             accion = "MODIFICAR";
             setControles(true);
             txt_Ibs.setEditable(false);
             mostrarDialogo();
          }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_CerrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarClientesActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btn_CerrarClientesActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        
        String estado;
        Connection con = conectarBD();
        
        if(accion.equals("ADICIONAR"))
        {
            try
             
            {
                String sSQL="INSERT INTO clientes VALUES (?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sSQL);

                

                pst.setString(1, txt_Ibs.getText());
                pst.setString(2, txt_Nombres.getText());
                pst.setString(3, txt_Direccion.getText());
                pst.setString(4, txt_Telefono.getText());
                pst.setString(5, txt_Municipio.getText());
                pst.setString(6, txt_Celular.getText());
                pst.setString(7, txt_Apellido.getText());
                
                JOptionPane.showMessageDialog(null, " "+txt_Ibs.getText()+" "+txt_Apellido.getText()+" "+txt_Nombres.getText()+" "+txt_Municipio.getText()+" "+txt_Direccion.getText()+" " +txt_Telefono.getText()+" "+txt_Celular.getText());

      
                pst.execute();
            }       
      
            catch (Exception e)
              {
               
                  
              
              }
        }    
        else if (accion.equals("MODIFICAR"))
        {
          
            try {
                String sSQL="update clientes set apellidos=?,nombres=?,municipio=?,direccion=?,telefono=?,celular=? where ibs=?";
                PreparedStatement pst = con.prepareStatement(sSQL);
                
                pst.setString(1, txt_Apellido.getText());
                pst.setString(2, txt_Nombres.getText());
                pst.setString(3, txt_Municipio.getText());
                pst.setString(4, txt_Direccion.getText());
                pst.setString(5, txt_Telefono.getText());
                pst.setString(6, txt_Celular.getText());
                pst.setString(7, txt_Ibs.getText());
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else
        {
            try
            {
                String sSQL = "DELETE FROM clientes WHERE ibs=?";
                
                PreparedStatement pst = con.prepareStatement(sSQL);
                
                pst.setString(1, txt_Ibs.getText());
                pst.execute();
                
            }
            catch ( Exception e )
            {
                JOptionPane.showMessageDialog(null, "Error al eliminar el cliente","Atencion",JOptionPane.WARNING_MESSAGE);
            }
        }
        
        cargarTabla("");
        desconectarBD();
        jdi_Clientes.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        
        String sSQL = "";
        String buscar = txt_Buscar.getText();
        int campo = cmb_Buscar.getSelectedIndex();
        
        if( campo == 0 )  // Todos
        {
           sSQL = "";
        }
        else if( campo == 1 ) // documento
        {
           sSQL =  " WHERE ibs LIKE '%"+buscar+"%'";
        }
        else if( campo == 2 ) // ibs
        {
           sSQL =  " WHERE apellidos LIKE '%"+buscar+"%'";
        }
        else if( campo == 3 ) //apellidos
        {
           sSQL =  " WHERE nombres LIKE '%"+buscar+"%'";
        }
        else if( campo == 4 ) // nombres
        {
           sSQL =  " WHERE municipio LIKE '%"+buscar+"%'";
        }
        else if( campo == 5 )
        {
           sSQL =  " WHERE direccion LIKE '%"+buscar+"%'";
        }
        else if( campo == 6 )
        {
           sSQL =  " WHERE telefono LIKE '%"+buscar+"%'";
        }
        else
        {
           sSQL =  " WHERE celular LIKE '%"+buscar+"%'";
        }
   
   
        cargarTabla(sSQL);
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void txt_IbsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IbsKeyTyped
        
        String caracter  = String.valueOf( evt.getKeyChar() );
        String cadena    = txt_Ibs.getText();
            
        if( !(caracter.matches("[0-9.]")) || cadena.length() > 14 )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_IbsKeyTyped

    private void txt_ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoKeyTyped
        
        String caracter  = String.valueOf( evt.getKeyChar() );
        String cadena    = txt_Apellido.getText();
        if( !(caracter.matches("[a-zA-Z. ]")) || cadena.length() > 99 )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_ApellidoKeyTyped

    private void txt_NombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombresKeyTyped
        
        String caracter  = String.valueOf( evt.getKeyChar() );
        String cadena    = txt_Nombres.getText();
        if( !(caracter.matches("[a-zA-Z. ]")) || cadena.length() > 99 )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_NombresKeyTyped

    private void txt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoKeyTyped
        
         String caracter  = String.valueOf( evt.getKeyChar() );
        String cadena    = txt_Telefono.getText();
        if( !(caracter.matches("[0-9- ]")) || cadena.length() > 19 )
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_TelefonoKeyTyped
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_CerrarClientes;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JComboBox cmb_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jdi_Clientes;
    private javax.swing.JTable jtb_Clientes;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Ibs;
    private javax.swing.JTextField txt_Municipio;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
