/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static clases.ConexionBD.conectarBD;
import static clases.ConexionBD.desconectarBD;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Luis
 */
public class DatosOrden extends javax.swing.JFrame {

   private String accion ="";
   
    public DatosOrden() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage();
        setIconImage(icon);
        
        cargarTabla("");
    }

    /*--------------------------------------------------------------------------------------------------
        MIS METODOS
        */
    
     public void cargarTabla(String condicion)
        {
            Connection con = conectarBD();
            ResultSet   rs = null;
            String[]   titulos = {"workorder","shipingorder","ibs","codigoservicio","serial","documento","numero_orden"};
            Object[]  fila = new Object[7]; 
            DefaultTableModel modelo = new DefaultTableModel(null,titulos);
            
            String sSQL  = "SELECT * FROM Datos de Orden"+condicion;
            
            try {
                
                PreparedStatement pst = con.prepareStatement(sSQL);
                rs=pst.executeQuery();
                
                while(rs.next ())
                {
                    fila[0] = rs.getString("workorder");
                    fila[1] = rs.getString("shipingorder");
                    fila[2] = rs.getString("ibs");
                    fila[3] = rs.getString("codigoservicio");
                    fila[4] = rs.getString("serial");
                    fila[5] = rs.getString("documento");
                    fila[6] = rs.getString("numero_orden");
                    modelo.addRow(fila);
                }  
                
                jtb_Datos.setModel(modelo);
            } 
            catch (Exception e) 
            {
            }
            desconectarBD();
        }
        
        public void mostrarDialogo()
        {
           Image icon = new ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage();
           jdi_DatosOrden.setIconImage(icon);
           jdi_DatosOrden.setLocationRelativeTo(this);
           jdi_DatosOrden.setSize(550,350);
           jdi_DatosOrden.setVisible(true);
        }
        
        public void setControles(boolean activo)
        {
           txt_Work.setEditable(activo);
           txt_Shiping.setEditable(activo);
           txt_Ibs.setEditable(activo);
           txt_Codigo.setEditable(activo);
           txt_Serial.setEditable(activo);
           txt_Documento.setEditable(activo);
           txt_NumOrden.setEditable(activo);
        }
        
        public void limpiarControles()
         
        {
            txt_Work.setText("");
            txt_Shiping.setText("");
            txt_Ibs.setText("");
            txt_Codigo.setText("");
            txt_Serial.setText("");
            txt_Documento.setText("");
            txt_NumOrden.setText("");
        }
        
        public boolean cargarDialogo()
        {
         int fila = jtb_Datos.getSelectedRow();  
        
        if( fila == -1 ) 
        {
            JOptionPane.showMessageDialog(null,"Debe seleccionar el Dato de Orden","Atencion",JOptionPane.WARNING_MESSAGE ); 
            return false;
        }
        else
        {
            DefaultTableModel modelo = new DefaultTableModel();
            
            modelo = (DefaultTableModel) jtb_Datos.getModel();
            
            txt_Work.setText( modelo.getValueAt(fila,0).toString());
            txt_Shiping.setText( modelo.getValueAt(fila,1).toString());
            txt_Ibs.setText( modelo.getValueAt(fila,2).toString() );
            txt_Codigo.setText( modelo.getValueAt(fila,3).toString());
            txt_Serial.setText( modelo.getValueAt(fila,4).toString());
            txt_Documento.setText( modelo.getValueAt(fila,5).toString());
            txt_NumOrden.setText( modelo.getValueAt(fila,6).toString());
            
           
            
            return true;
         }  
    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdi_DatosOrden = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Work = new javax.swing.JTextField();
        txt_Shiping = new javax.swing.JTextField();
        txt_Ibs = new javax.swing.JTextField();
        txt_Codigo = new javax.swing.JTextField();
        txt_Serial = new javax.swing.JTextField();
        txt_Documento = new javax.swing.JTextField();
        txt_NumOrden = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_Buscar = new javax.swing.JComboBox();
        txt_Buscar = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Datos = new javax.swing.JTable();
        btn_Adicionar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_CerrarDatos = new javax.swing.JButton();

        jLabel3.setText("workorder:");

        jLabel4.setText("Shipingorder:");

        jLabel5.setText("ibs:");

        jLabel6.setText("Codigo del servicio:");

        jLabel7.setText("Serial:");

        jLabel8.setText("Documento:");

        jLabel9.setText("Documento Orden:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciudad.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Datos de la orden de servicio:");

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");

        btn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdi_DatosOrdenLayout = new javax.swing.GroupLayout(jdi_DatosOrden.getContentPane());
        jdi_DatosOrden.getContentPane().setLayout(jdi_DatosOrdenLayout);
        jdi_DatosOrdenLayout.setHorizontalGroup(
            jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel11)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdi_DatosOrdenLayout.createSequentialGroup()
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_Aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cerrar))
                    .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Work)
                            .addComponent(txt_Shiping)
                            .addComponent(txt_Ibs)
                            .addComponent(txt_Codigo)
                            .addComponent(txt_Serial)
                            .addComponent(txt_Documento)
                            .addComponent(txt_NumOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addGap(66, 66, 66))
        );
        jdi_DatosOrdenLayout.setVerticalGroup(
            jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGap(36, 36, 36)
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Work, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Shiping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Ibs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdi_DatosOrdenLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_NumOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jdi_DatosOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Cerrar))
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Datos Orden De Servicio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        cmb_Buscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "todos", "workorder", "shipingorder", "ibs", "Codigo de servicio", "serial", "documento", "numero de orden" }));

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N

        jtb_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtb_Datos);

        btn_Adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adicionar.png"))); // NOI18N
        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_CerrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btn_CerrarDatos.setText("Cerrar");
        btn_CerrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btn_Adicionar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_Editar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Eliminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_CerrarDatos))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Buscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Adicionar)
                    .addComponent(btn_Editar)
                    .addComponent(btn_Eliminar)
                    .addComponent(btn_CerrarDatos))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        
        accion ="ADICIONAR";
        mostrarDialogo();
        setControles(true);
        limpiarControles();
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        
        jdi_DatosOrden.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        
        if( cargarDialogo())
          {
             accion = "MODIFICAR";
             setControles(true);
             txt_Work.setEditable(false);
             mostrarDialogo();
          }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        
         if( cargarDialogo() )
        {
           cargarDialogo(); 
           accion = "ELIMINAR";
           setControles(false);
           mostrarDialogo();
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_CerrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarDatosActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btn_CerrarDatosActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        
        String estado;
        Connection con = conectarBD();
        
        if(accion.equals("ADICIONAR"))
        {
            try
             
            {
                String sSQL="INSERT INTO Datos de orden VALUES (?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sSQL);

                

                pst.setString(1, txt_Work.getText());
                pst.setString(2, txt_Shiping.getText());
                pst.setString(3, txt_Ibs.getText());
                pst.setString(4, txt_Codigo.getText());
                pst.setString(5, txt_Serial.getText());
                pst.setString(6, txt_Documento.getText());
                pst.setString(7, txt_NumOrden.getText());
                
                JOptionPane.showMessageDialog(null, " "+txt_Work.getText()+" "+txt_Shiping.getText()+" "+txt_Ibs.getText()+" " +txt_Codigo.getText()+" "+txt_Serial.getText()+" "+txt_Documento+" "+txt_NumOrden);

      
                pst.execute();
            }       
      
            catch (Exception e)
              {
               
                  
              
              }
        }    
        else if (accion.equals("MODIFICAR"))
        {
          
            try {
                String sSQL="update Datos de Orden set workorder=?,Shipingorder=?,ibs=?,codigo=?,serial=?,documento=? where numero_orden=?";
                PreparedStatement pst = con.prepareStatement(sSQL);
                
                pst.setString(1, txt_Work.getText());
                pst.setString(2, txt_Shiping.getText());
                pst.setString(3, txt_Ibs.getText());
                pst.setString(4, txt_Codigo.getText());
                pst.setString(5, txt_Serial.getText());
                pst.setString(6, txt_Documento.getText());
                pst.setString(7, txt_NumOrden.getText());
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(DatosOrden.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        else
        {
            try
            {
                String sSQL = "DELETE FROM datos_orden_de_servicio WHERE cli_documento=?";
                
                PreparedStatement pst = con.prepareStatement(sSQL);
                
                pst.setString(1, txt_Work.getText());
                pst.execute();
                
            }
            catch ( Exception e )
            {
                JOptionPane.showMessageDialog(null, "Error al eliminar el Dato de orden","Atencion",JOptionPane.WARNING_MESSAGE);
            }
        }
        
        cargarTabla("");
        desconectarBD();
        jdi_DatosOrden.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_CerrarDatos;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JComboBox cmb_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jdi_DatosOrden;
    private javax.swing.JTable jtb_Datos;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_Documento;
    private javax.swing.JTextField txt_Ibs;
    private javax.swing.JTextField txt_NumOrden;
    private javax.swing.JTextField txt_Serial;
    private javax.swing.JTextField txt_Shiping;
    private javax.swing.JTextField txt_Work;
    // End of variables declaration//GEN-END:variables
}
